export const UPDATE_PHOTO_COUNT = "UPDATE_PHOTO_COUNT";
export const UPDATE_DIMENSION = "UPDATE_DIMENSION";
export const UPDATE_GRAYSCALE = "UPDATE_GRAYSCALE";
export const UPDATE_BLUR = "UPDATE_BLUR";
